### PR TITLE
Frontend log

### LINKED ISSUE #334: Frontend critical logs to cloudwatch
**Feature Overview**
Frontend errors (React crashes, API failures, unhandled rejections) are only visible in the browser console. A lightweight pipeline is needed: frontend batches errors, POSTs them to a new backend endpoint, backend logs them with a `[FRONTEND]` prefix so they appear in existing CloudWatch log groups alongside backend logs.

**Priority**
Classify the importance of this feature as [Low, Medium, High].
- Low: This feature is not included in the minimum development requirements.

[PLAN_FRONTEND_LOGS.md](https://github.com/user-attachments/files/25434735/PLAN_FRONTEND_LOGS.md)

### PR DESCRIPTION
**Pull request by milesAraya**
#### Summary
- Premium users assigned to the temporary `autoscaling-pool` fallback get stuck in an infinite retry loop when dedicated instances become available. The assign endpoint detects the shared assignment, fires an async migration Lambda, and returns `is_shared: True`. The frontend sees this and retries assignment, but the async migration never completes because the migration lock is already held or times out.
- The fix adds inline migration to the assign endpoint: when a user has an `autoscaling-pool` or shared assignment and a dedicated instance is ready and unoccupied, the endpoint migrates the user synchronously and returns the new dedicated assignment with `is_shared: False`, breaking the loop.
- Async migration is retained as a fallback for cases where no dedicated instance is ready yet (e.g., still booting).

#### Design Decisions
- **Inline migration in the assign path instead of fixing the async lock** -- The async migration architecture has multiple failure modes (60-second lock timeout, 10-minute max wait, lock contention between concurrent invocations). Rather than patching the lock mechanism, the assign endpoint now resolves the common case (instances are running but user is stuck on autoscaling-pool) directly. This is simpler and gives the user immediate feedback.
- **Short readiness timeout (10s) for inline migration** -- The inline check uses `max_wait_seconds=10` vs the normal 30s to avoid blocking the assign HTTP response. If no instance passes readiness in 10s, the code falls through to async migration, so no functionality is lost.
- **Async migration kept as safety net** -- If all dedicated instances are still booting (no candidates pass readiness), the existing `invoke_migration_async()` path still fires. This preserves the original behavior for cold-start scenarios.

#### Observed failure (2026-03-24 19:15 UTC)

Initial assignment — all premium instances stopped, user 33 gets autoscaling-pool fallback:
```
2026-03-24 19:15:35,053  assign_premium_user():154 - Assigning premium user 33 (uid: xnUWJG0uQDW8ycrwktKUszHfT5E3) to dedicated instance
2026-03-24 19:15:54,192  assign_premium_user():234 - Successfully assigned premium user 33 to instance autoscaling-pool
```

Frontend sees `is_shared: True`, retries, creating the loop:
```
2026-03-24 19:15:54,342  log_premium_ui_event():421 - Premium UI event: user=33 event=waiting_popup_shown details={'is_assigning': False, 'has_assignment': True, 'is_shared': True, 'instance_id': 'autoscaling-pool'}
2026-03-24 19:16:24,337  assign_premium_user():154 - Assigning premium user 33 (uid: xnUWJG0uQDW8ycrwktKUszHfT5E3) to dedicated instance
```

Lambda confirms user is stuck — migration lock held, skipped:
```
User 33 already has active assignment to instance autoscaling-pool
User 33 needs migration (instance=autoscaling-pool, shared=1), triggering migration check...
Lock 'migrate_users_lock' is held
Migration Lambda already running, skipping
```

Meanwhile, 3 premium instances were running and available:
```
Instance discovery summary:
- Premium instances matched: 3
- States: [('i-075b57d1ac079df9a', 'running'), ('i-0158d4868c2c5c26d', 'running'), ('i-09a04004643ea3431', 'running')]
```

The assign endpoint returned `autoscaling-pool` with `is_shared: True` on every call despite running dedicated instances being available.

### References
- Manual fix applied: released user 33's stale assignment via `aws lambda invoke` with `action: release`

#### Files changed
- `infrastructure/terraform/premium_manager_package/premium_manager.py` -- Add inline migration attempt in `assign_premium_user()` when user has autoscaling-pool or shared assignment; scans running instances for a ready, unoccupied candidate and calls `migrate_user_to_dedicated_instance()` synchronously before falling back to async migration

### Manual Testcases

Check log for FRONTEND

Screenshot 2026-03-26 at 15 31 28

### Unit, Integration, Contract Test Coverage
- `infrastructure/scripts/test_premium_lambda.py` -- existing Lambda integration tests cover the `assign` action path
- No unit test for inline migration path yet; the migration function `migrate_user_to_dedicated_instance()` is already tested in `studio/tests/infrastructure/test_premium_manager.py`

#### Difficulties
- The root cause was non-obvious: the assign endpoint, async migration Lambda, and frontend retry loop formed a three-way deadlock. The assign endpoint always returned the stale shared assignment, the migration Lambda couldn't acquire the lock, and the frontend kept retrying because it saw `is_shared: True`.

#### Risk Assessment
| Area | Risk | Notes |
|------|------|-------|
| Inline migration in assign path | Medium | Adds EC2 readiness checks and a migration call to the synchronous assign path, increasing latency by up to 10s when migration is attempted. If `migrate_user_to_dedicated_instance()` fails, falls through to existing async path — no regression. |
| Readiness timeout (10s) | Low | Shorter than the normal 30s check. Worst case: a ready instance is missed and async migration handles it. No false positives. |
| Concurrent assign calls | Low | `migrate_user_to_dedicated_instance()` uses database-level locking via `try_reserve_instance_for_migration()`. Two concurrent inline migrations for the same user would not both succeed. |

### CODE REVIEW

File: frontend/src/components/Workspace/FlowChart/ModalLogs/helpers/service.ts [hunk 1]
```diff
@@ -10,6 +10,7 @@ export enum TLevelsLog {
   DEBUG = "DEBUG",
   WARNING = "WARNING",
   CRITICAL = "CRITICAL",
+  FRONTEND = "FRONTEND",
```
Comment (itutu-tienday) [inline frontend/src/components/Workspace/FlowChart/ModalLogs/helpers/service.ts:13]: Strictly speaking, "FRONTEND" is not a log level, so it might be best to avoid mixing them here.

*If it were something like "ERROR_FRONTEND," it would seem to be a log level, but would configuring it that way be consistent with the design?

File: frontend/src/utils/__tests__/errorReporter.test.ts [hunk 2]
```diff
@@ -0,0 +1,195 @@
...
+} from "@jest/globals"
+
+let mockTokenValue = "test-token"
+
+jest.mock("utils/auth/AuthUtils", () => ({
+  getToken: () => mockTokenValue,
+}))
+
+jest.mock("const/API", () => ({
+  BASE_URL: "http://localhost:8000",
```
Comment (itutu-tienday) [inline frontend/src/utils/__tests__/errorReporter.test.ts]: Is it necessary to hardcode this URL here? (Even after grepping, I don't see any similar code in other files.)

File: frontend/src/utils/__tests__/errorReporter.test.ts [hunk 3]
```diff
@@ -0,0 +1,195 @@
...
+    expect(_getQueue()[0].message.length).toBe(MAX_MESSAGE_LENGTH)
+  })
+
+  it("calls fetch with correct shape on flush", () => {
+    initErrorReporter()
+    console.error("test")
+    flushErrors()
+
+    expect(fetchSpy).toHaveBeenCalledWith(
+      "http://localhost:8000/users/me/frontend-errors",
```
Comment (itutu-tienday) [inline frontend/src/utils/__tests__/errorReporter.test.ts]: Is it necessary to hardcode this URL here?

File: infrastructure/documentation/LOGGING_ARCHITECTURE.md [hunk 4]
```diff
@@ -768,11 +768,30 @@ The free manager also triggers on ASG lifecycle events (instance launch/terminat
 
 **Guarantee:** All workers get the same log level.
 
-### 6. Frontend Logs Are Not Collected
+### 6. Frontend Error Forwarding
```
Comment (itutu-tienday) [inline infrastructure/documentation/LOGGING_ARCHITECTURE.md:771]: It appears that the following comment remains elsewhere:

> There is no server-side collection of frontend logs.

File: studio/app/common/core/utils/log_reader.py [hunk 5]
```diff
@@ -17,6 +19,7 @@ class LogLevel(str, Enum):
     DEBUG = "DEBUG"
     WARNING = "WARNING"
     CRITICAL = "CRITICAL"
+    FRONTEND = "FRONTEND"
```
Comment (itutu-tienday) [inline studio/app/common/core/utils/log_reader.py:22]: Same as bellow:
- https://github.com/arayabrain/araya-optinist/pull/417#discussion_r2980671855

File: studio/app/common/routers/users_me.py [hunk 6]
```diff
@@ -404,6 +407,95 @@ async def send_premium_heartbeat(current_user: User = Depends(get_current_user))
         }
 
 
+FRONTEND_VALID_LEVELS = ("error", "warn")
```
Comment (itutu-tienday) [inline studio/app/common/routers/users_me.py]: Are the definitions of these constants and functions appropriate within this module? (Or should they not be defined in the logging modules?)

File: frontend/src/components/Workspace/FlowChart/ModalLogs/helpers/service.ts (hunk 1 above)
Comment (milesAraya) [reply frontend/src/components/Workspace/FlowChart/ModalLogs/helpers/service.ts:13]: For me FRONTEND seems easier for users and developers, rather than 
ERROR_FRONTEND and WARNING_FRONTEND. Those are very long names making GUI less clean, and adds more filters than needed. The very minor issue is in our naming of "TLevelsLog", but this is not an issue for users

File: frontend/src/utils/__tests__/errorReporter.test.ts (hunk 2 above)
Comment (milesAraya) [reply frontend/src/utils/__tests__/errorReporter.test.ts]: Moved to magic url MOCK_BASE_URL

File: frontend/src/utils/__tests__/errorReporter.test.ts (hunk 3 above)
Comment (milesAraya) [reply frontend/src/utils/__tests__/errorReporter.test.ts]: Use MOCK_BASE_URL

File: infrastructure/documentation/LOGGING_ARCHITECTURE.md (hunk 4 above)
Comment (milesAraya) [reply infrastructure/documentation/LOGGING_ARCHITECTURE.md:771]: Updated

File: studio/app/common/core/utils/log_reader.py (hunk 5 above)
Comment (milesAraya) [reply studio/app/common/core/utils/log_reader.py:22]: See comment above

File: studio/app/common/routers/users_me.py (hunk 6 above)
Comment (milesAraya) [reply studio/app/common/routers/users_me.py]: Moved all to new frontend_errors.py router

File: frontend/src/components/Workspace/FlowChart/ModalLogs/helpers/service.ts (hunk 1 above)
Comment (itutu-tienday) [reply frontend/src/components/Workspace/FlowChart/ModalLogs/helpers/service.ts:13]: If it's being used as a UI label (which seems to be the current case), then including "FRONTEND" in the list shouldn't cause any problems.

In the future, if the need arises to precisely define the log level due to feature enhancements or other reasons, it would be good to replace it with the accurate definition.

File: studio/app/common/routers/frontend_errors.py [hunk 7]
```diff
@@ -0,0 +1,102 @@
...
+
+from fastapi import APIRouter, Depends, HTTPException, status
+from pydantic import BaseModel, Field
+
+from studio.app.common.core.auth.auth_dependencies import get_current_user
+from studio.app.common.core.logger import AppLogger
+from studio.app.common.core.utils.log_reader import FRONTEND_LOG_PREFIX
+from studio.app.common.schemas.users import User
+
+router = APIRouter(prefix="/users/me", tags=["logs"])
```
Comment (itutu-tienday) [inline studio/app/common/routers/frontend_errors.py]: It would be a good idea to replace this prefix with an appropriate one (a prefix indicating the logging API).

File: studio/app/common/routers/log_report.py [hunk 8]
```diff
@@ -0,0 +1,102 @@
+import time
```
Comment (itutu-tienday) [inline studio/app/common/routers/log_report.py:1]: This is a minor point, but perhaps a more generic name (one that doesn't include "frontend") would be better for this module.
-> For example, something like "log_report".

File: studio/app/common/routers/users_me.py (hunk 6 above)
Comment (itutu-tienday) [reply studio/app/common/routers/users_me.py]: Okay. I've just added some minor comments regarding the API prefix and module name.

File: frontend/src/utils/__tests__/errorReporter.test.ts [hunk 9]
```diff
@@ -0,0 +1,195 @@
...
+    expect(_getQueue()[0].message.length).toBe(MAX_MESSAGE_LENGTH)
+  })
+
+  it("calls fetch with correct shape on flush", () => {
+    initErrorReporter()
+    console.error("test")
+    flushErrors()
+
+    expect(fetchSpy).toHaveBeenCalledWith(
+      "http://test-host:9999/users/me/frontend-errors",
```
Comment (itutu-tienday) [inline frontend/src/utils/__tests__/errorReporter.test.ts]: Is it appropriate to apply BASE_URL in this section as well?

**Review by itutu-tienday — COMMENTED** [review]
I think it's mostly OK, but I've added a few more points.

*Regarding the API naming (prefix and module name), I think it would be best if you could make final adjustments.

File: studio/app/common/routers/frontend_errors.py (hunk 7 above)
Comment (milesAraya) [reply studio/app/common/routers/frontend_errors.py]: Changed the prefix from /users/me to /logs, so the endpoint is now /logs/frontend-errors. Similar to logs.py router

File: frontend/src/utils/__tests__/errorReporter.test.ts (hunk 9 above)
Comment (milesAraya) [reply frontend/src/utils/__tests__/errorReporter.test.ts]: Done

File: studio/app/common/routers/log_report.py (hunk 8 above)
Comment (milesAraya) [reply studio/app/common/routers/log_report.py:1]: Renamed the module to log_report.py (and the test files to test_log_report.py / test_log_report_api_contract.py).

File: studio/app/common/routers/frontend_errors.py (hunk 7 above)
Comment (itutu-tienday) [reply studio/app/common/routers/frontend_errors.py]: The proposed fix is ​​good, but it appears that `prefix="/logs"` is conflicting with the following existing module.

While there seem to be no issues at the moment, unexpected conflicts may arise in the future, so it would be best to fix it at this stage if possible.

**Review by itutu-tienday — APPROVED** [review]
I've approved it for now, but I've pointed out one more thing.
If possible, please make the necessary adjustments.
