### PR TITLE
Update console -> dashboard, renaming, fix misspelling

### LINKED ISSUE #172: Update Console / Dataview
### Summary

- Change /console to /dashboard
- Left side menu "Open Site" changed to "Public Repository"
- "Studio Dataview" changed to "OptiNiSt Public Repository"
- STUDIO changes to "OptiNiSt"
- Workflolw Outputs -> Workflow Outputs
- Dataview shows "LOGIN" when not logged in, and "DASHBOARD" when logged in.
- /dataview changed to /public

### PR DESCRIPTION
**Pull request by milesAraya**
### Content

- Change /console to /dashboard
- Left side menu "Open Site" changed to "Public Repository" 
- "Studio Dataview" changed to "OptiNiSt Public Repository"
- STUDIO changes to "OptiNiSt"
- Workflolw Outputs -> Workflow Outputs 
- Dataview shows "LOGIN" when not logged in, and "DASHBOARD" when logged in. 
- /dataview changed to /public

#### Logged Out State:
- [x]   /workspaces redirects to /login
- [x]   /workspaces/:id redirects to /login
- [x]   /dashboard redirects to /login
- [x]   /account redirects to /login
- [x]   /account-manager redirects to /login
- [x]   /subscription redirects to /login
- [x]   /subscription/manage redirects to /login

#### Logged in state:

- [x]   /login redirects to /dashboard after login
- [x]   /register accessible (or redirects if already logged in)
- [x]  /public accessible while logged in
- [x]  / redirects to /public (even when logged in)
- [x] DASHBOARD displayed instead of LOGIN 

Dashboard page
- [x] /dashboard -> /account
- [x] /dashboard -> /workspaces
- [x]  /dashboard -> /dataview (Personal user data dataview)
- [x] /dashboard -> /account-manager
- [x]  /dashboard -> /subscription

Workspace Page (/workspaces/:id):
- [x]  WORKFLOW tab displays and is functional
- [x]  VISUALIZE tab displays and is functional
- [x]   RECORD tab displays and is functional
- [x]  "Exit to Workspaces" tab/button navigates to /workspaces

Workspace List (/workspaces):
- [x]  Can create new workspace
- [x]  Can view workspace list
- [x]  Clicking workspace name navigates to /workspaces/:id (WORKFLOW tab)
- [x]  "Records" button navigates to /workspaces/:id with RECORD tab active
- [x]  "Dataview" button navigates to /dataview/:id
- [x]  Can edit workspace name
- [x]  Can delete workspace
- [x]  Can share workspace

Left Menu Navigation (when logged in)
- [x]  Left menu "Dashboard" → /dashboard
- [x]  Left menu "Workspaces" → /workspaces
- [x]  Left menu "Dataview" → /dataview
- [x]  Left menu "Account" → /account
- [x]  Left menu "Account Manager" → /account-manager (if admin)
- [x]  Left menu "Upgrade plan" → /subscription

Subscription Flow
- [x]  /subscription/thanks accessible after successful payment
- [x]  /subscription/failed accessible after failed payment
- [ ]  /subscription/manage shows invoices correctly

Edge Cases
- [x]  Invalid workspace ID redirects to workspaces
- [x] /account-deleted page accessible without auth
- [x]  /reset-password page accessible without auth

image

Screenshot 2025-11-21 at 16 50 53

image

### CODE REVIEW

**Review by tsuchiyama-araya — CHANGES_REQUESTED** [review]
LGTM

(Sorry I misclick Request Changes)

**Review by tsuchiyama-araya — APPROVED** [review]

File: frontend/src/pages/Dashboard/index.tsx [hunk 1]
```diff
@@ -26,15 +26,15 @@ const Dashboard = () => {
       <h1 style={{ paddingLeft: 16 }}>Dashboard</h1>
       <DashboardWrapper>
         <DashboardContent>
-          <LinkWrapper to="/console/dataview">
+          <LinkWrapper to="/dashboard/public">
```
Comment (itutu-tienday) [inline frontend/src/pages/Dashboard/index.tsx]: `/dashboard/public` does not seem correct.
For example, `/dashboard/repository` would still seem reasonable (terminology needs to be standardized).

File: frontend/src/App.tsx [hunk 2]
```diff
@@ -69,40 +69,46 @@ const App: FC = () => {
...
-              <Route path="/dataview" element={<PublicDataview />} />
+              <Route path="/" element={<Navigate replace to="/public" />} />
+              <Route path="/public" element={<PublicDataview />} />
               <Route path="/account-deleted" element={<AccountDelete />} />
               <Route path="/login" element={<Login />} />
               <Route path="/register" element={<RegistrationForm />} />
               <Route path="/reset-password" element={<ResetPassword />} />
-              <Route path="/console" element={<Dashboard />} />
-              <Route path="/console/account" element={<Account />} />
+              <Route path="/dashboard" element={<Dashboard />} />
```
Comment (itutu-tienday) [inline frontend/src/App.tsx:81]: - "Dashboard" should only refer to the top screen of the management console.
- Wouldn't changing just the title of the top page meet the requirements of the issue?
- Even if the URL is also corrected, wouldn't the requirement be met by at least changing the top page URL from `/console` to `/console/dashboard` (a minor adjustment)?

**Review by itutu-tienday — CHANGES_REQUESTED** [review]

File: frontend/src/pages/Dashboard/index.tsx (hunk 1 above)
Comment (milesAraya) [reply frontend/src/pages/Dashboard/index.tsx]: Maybe I have missed something important here. Could you explain why /dashboard/public is incorrect but /dashboard/repository is acceptable?

Comment (itutu-tienday) [reply frontend/src/pages/Dashboard/index.tsx]: Yes, I've used the keyword `/dashboard` for now, but the URLs I think would be appropriate are:

1. `/console/dataview` (same as it is)
2. or `/console/repository` (Because the name "public repository" seems to be used)

Comment (milesAraya) [reply frontend/src/pages/Dashboard/index.tsx]: The term dataview is not appropriate as it is unclear for users. 

Image the situation that a new user scans a QR code tries to access 
https://araya-optinist.com/

It is considered to be confusing to be redirected to https://araya-optinist.com/dataview

Instead 
https://araya-optinist.com/public, which holds the publicly visible data, seems most appropriate. 

public seems more understandable than repository for a new user who is not an engineer and has no knowledge of optinist at that time.

Comment (itutu-tienday) [reply frontend/src/pages/Dashboard/index.tsx]: Yes, I think there's no problem with using "public" for the URL of the public screen.

Here, I pointed out the URL under the management console (/dashboard/public).
(Even though it's under the management console (!= public), it feels strange to use "public" for the URL.)

File: frontend/src/components/Layout/index.tsx [hunk 3]
```diff
@@ -19,7 +19,23 @@ import { selectCurrentUser } from "store/slice/User/UserSelector"
 import { AppDispatch } from "store/store"
 import { getToken } from "utils/auth/AuthUtils"
 
-const authRequiredPathRegex = /^\/console\/?.*/
+// Public routes that don't require authentication
+const PUBLIC_ROUTES = [
```
Comment (milesAraya) [inline frontend/src/components/Layout/index.tsx]: Move to AuthUtils

File: frontend/src/components/Workspace/WorkspaceTabs.tsx [hunk 4]
```diff
@@ -70,7 +70,7 @@ const WorkspaceTabs: FC = () => {
                 </span>
               </span>
             }
-            onClick={() => navigate("/console/workspaces")}
+            onClick={() => navigate("/workspaces")}
```
Comment (itutu-tienday) [inline frontend/src/components/Workspace/WorkspaceTabs.tsx:73]: I'm not sure if this fix is the cause, but have the tabs disappeared?

image

File: frontend/src/pages/Dashboard/index.tsx (hunk 1 above)
Comment (itutu-tienday) [reply frontend/src/pages/Dashboard/index.tsx]: Confirmed that the URL of the dataview page under dashboard remains `/dataview`.

File: frontend/src/components/Layout/index.tsx (hunk 3 above)
Comment (itutu-tienday) [reply frontend/src/components/Layout/index.tsx]: Please let me know after you fix it

File: frontend/src/App.tsx (hunk 2 above)
Comment (itutu-tienday) [reply frontend/src/App.tsx:81]: As a result, the decision was made to remove the `/console` URL prefix.

File: frontend/src/components/Workspace/WorkspaceTabs.tsx (hunk 4 above)
Comment (itutu-tienday) [inline frontend/src/components/Workspace/WorkspaceTabs.tsx:73]: Considering the above issue (and its impact on existing functionality), it's a good idea to add the following to your test cases:

- Verify that all existing functions are working properly (check whether changes to screen URLs are linked to the operation of each function).
- Verify that authentication control is being applied as expected to all screens (which are not many) in both the unsigned and signed-in states.

Comment (milesAraya) [reply frontend/src/components/Workspace/WorkspaceTabs.tsx:73]: Fixed

File: frontend/src/components/Layout/index.tsx (hunk 3 above)
Comment (milesAraya) [reply frontend/src/components/Layout/index.tsx]: Done

**Review by itutu-tienday — APPROVED** [review]
