### PR TITLE
Fix Paying with Link Stripe Does Not Show Payment Method in OpiNiSt

### LINKED ISSUE #316: Paying with Link Stripe Does Not Show Payment Method in OpiNiSt
### Summary

Paying with Link Stripe Does Not Show Payment Method in OpiNiSt

### Tasks

- [x] Update code to show payment method with Stripe Link

### References

TC-305
https://docs.google.com/spreadsheets/d/1bq0ySUQCnmSc9Lh5PUnfIKcS00fFCvpbDs_e797Z8W4/edit?gid=401702244#gid=401702244

### PR DESCRIPTION
**Pull request by tsuchiyama-araya**
### Content

Fix Paying with Link Stripe Does Not Show Payment Method in OpiNiSt

### References

TC-305
https://docs.google.com/spreadsheets/d/1bq0ySUQCnmSc9Lh5PUnfIKcS00fFCvpbDs_e797Z8W4/edit?gid=401702244#gid=401702244

### Testcase

- [x] Create user and upgrade using Stripe Link. Check Account Profile Manage Subscription page if Payment Method showing Stripe Link with Email
- [x] Create user and upgrade using Stripe Test Card. Check Account Profile Manage Subscription page if Payment Method showing Last 4 Numbers of card

Screenshot 2026-02-17 at 13 19 39

### CODE REVIEW

File: frontend/src/pages/Invoice/index.tsx [hunk 1]
```diff
@@ -552,12 +552,26 @@ const InvoicesPage: FC = () => {
                   </FlexRow>
                 ) : paymentMethod ? (
                   <FlexRow>
-                    <CardIcon brand={paymentMethod.brand}>
-                      <CardBrandIcon brand={paymentMethod.brand} size={32} />
+                    <CardIcon
```
Comment (itutu-tienday) [inline frontend/src/pages/Invoice/index.tsx:555]: Please attach a screenshot image to your PR description to see the changes before and after the fix.

**Review by itutu-tienday — APPROVED** [review]
There is a comment pointing out one thing about the test results, but we will prioritize deploy & test and approve it at this point.

File: frontend/src/pages/Invoice/index.tsx (hunk 1 above)
Comment (tsuchiyama-araya) [reply frontend/src/pages/Invoice/index.tsx:555]: I added it
