### PR TITLE
Add 503 error fix

### LINKED ISSUE #436: 503 error in routing for premium user
## Problem

Premium user で sign in 後、以下の操作で 503 エラーが発生し、以降browser上では操作を復帰できない状況が、確認されている

#### 再現手順

1. premium user で sign in
    1. 新規 premium instance 割り当て ok
    2. 対象の premium instance を ec2 console から強制停止
2. premium user は browser reload すると 503 error (復帰せず)
    1. 別の browser (sercret mode) で、premium 3 に再度 sign in
    2. 10分待機したが、premium instance へ割り当てられず
3. browser をreloadすると、503 error となり、復帰不可能となる （chrome, safari, で browser によらず発生している）
4. その後、約20分経過すると、premium instance への assign が実施された

#### 一次調査

- AI report (現状の仕様の可能性？)

>   Root cause of the coworker's 503: The instance was force-stopped (not terminated). The liveness check only caught                    
>   terminated/shutting_down/None, so get_premium_user_status returned 200 with the stopped instance. The frontend set routing headers
>   pointing at it → every request got 503. Recovery only happened ~20 minutes later when the 15-minute monitoring cycle cleaned it up.  
>                                                             
>   Fix: Added InstanceState.STOPPED and InstanceState.STOPPING to both liveness checks:                                                 
>   1. get_premium_user_status (line 1802) — status endpoint now detects stopped instances, cleans up, returns 404 → frontend triggers
>   fresh assign                                                                                                                         
>   2. _restore_pending_release_transaction (line 675) — prevents restoring a pending_release assignment that points to a stopped  instance

#### 再現手順

- 正確な再現手順は不明確だが、client (browser) に保存されている token (for alb routing) が不整合となった場合に、alb routing が行えない状況（503 error）が生じる
- このケースが発生すると、token の有効期限切れとなるまでは、復帰が不能となる

## 対策

- [x] ケース1) への対策
  - 以下で解消されている見込み
    - #439

- [x] ケース1) への対策（追加改善）
  - #439 で基本的な対策は行われたが、以下の課題があり、追加改善が望まれる
    - 503 error を全て共有エラー処理しているが（axios.js）、ALB と optinist の 発生源を識別したエラー処理が必要

- [x] ケース2) への対策
  - ケース1) の対策では、解消されていない想定
  - 発生頻度は低いと見られるが、別途対策が必要
    - 「一定回数 ALB から errorが返された場合にはエラーページを表示する」等
    - #502 にて対処

### PR DESCRIPTION
**Pull request by tsuchiyama-araya**
#### Summary
- When a premium user hits a 503 (ALB target group empty/unhealthy), the axios interceptor retries on the free tier but does not clear the `premiumAssigned` flag.
- Subsequent requests continue sending stale premium routing headers (`X-User-Tier`, `X-Routing-ID`), causing repeated 503s until the user refreshes the page.
- This fix calls `routingService.setPremiumAssigned(false)` before the fallback retry, so all subsequent requests route through the free tier until the premium instance is reassigned.

#### Design Decisions
- **Clear flag before retry, not after**: Clearing `premiumAssigned` before the retry ensures that any concurrent requests initiated while the retry is in-flight also route to the free tier, avoiding a window where parallel requests still hit the dead premium target group.
- **No distinction between ALB 503 and backend 503**: Backend endpoints (e.g., `dataview.py`, `roi.py`) can also return 503 for data-unavailability reasons. For premium users, these will trigger one unnecessary free-tier retry before surfacing the same error. This is harmless (no state change, same error returned) and was accepted because ALB-level vs backend-level 503s are indistinguishable from the response alone. A custom header (e.g., `X-Error-Source`) could be added later if the extra round-trip becomes a concern.
- **`_retryWithoutPremium` guard unchanged**: The existing infinite-loop guard prevents cascading retries; no changes needed there.

### Evidence
- Before fix: premium user encounters 503 -> fallback succeeds -> next request sends stale premium headers -> 503 again -> repeats until page refresh
- After fix: premium user encounters 503 -> flag cleared -> fallback succeeds -> subsequent requests use free tier headers -> no repeated 503s

### References
- Related: #439 (error message splitting), #440 (premium manager stale assignment fixes)
- Backend 503 sources: `studio/app/common/routers/dataview.py:292`, `studio/app/optinist/routers/roi.py:59`

#### Files changed
- `frontend/src/utils/axios.ts` -- Add `routingService.setPremiumAssigned(false)` in `handlePremiumRoutingError` before building the retry config, clearing stale premium routing state

### Manual Testcases
1. Premium user with an active premium instance: stop the premium instance (or drain the target group) so ALB returns 503
2. Navigate to any page that triggers an API call -> expect: request fails with 503, interceptor retries on free tier, page loads with free-tier data
3. Navigate to another page -> expect: request goes directly to free tier (no 503), confirming `premiumAssigned` was cleared
4. Reassign premium instance -> expect: after `/premium/assign` succeeds, subsequent requests resume premium routing

### Unit, Integration, Contract Test Coverage
- Existing `frontend/src/utils/__tests__/axios.test.ts` covers the 503 interceptor fallback path

#### Risk Assessment
| Area | Risk | Notes |
|------|------|-------|
| Frontend routing | Low | Single flag change, guarded by `requiresPremiumRouting()` check; only affects premium users |
| Backend 503 overlap | Low | Unnecessary retry is harmless (idempotent GET, same error returned); no state mutation |

### CODE REVIEW

File: frontend/src/utils/axios.ts [hunk 1]
```diff
@@ -214,6 +214,10 @@ const handlePremiumRoutingError = async (
   }
 
   // Premium instance not ready, falling back to free tier.
+  // Clear premiumAssigned so subsequent requests don't keep sending
```
Comment (itutu-tienday) [inline frontend/src/utils/axios.ts:217]: Please review and address the following issue:
- https://github.com/arayabrain/araya-optinist/issues/436#issuecomment-4158928924

Comment (milesAraya) [reply frontend/src/utils/axios.ts:217]: Would this be addressed by https://github.com/arayabrain/araya-optinist/pull/439?

Comment (itutu-tienday) [reply frontend/src/utils/axios.ts:217]: > Would this be addressed by #439?

This should be covered by 439.

@tsuchiyama-araya 
If transferring to 439 is acceptable, please close this PR.

Comment (milesAraya) [reply frontend/src/utils/axios.ts:217]: I think we still need this PR, I am saying the concern raised in https://github.com/arayabrain/araya-optinist/issues/436#issuecomment-4158928924 is addressed in https://github.com/arayabrain/araya-optinist/pull/439

**Review by milesAraya — APPROVED** [review]

File: frontend/src/utils/axios.ts (hunk 1 above)
Comment (itutu-tienday) [reply frontend/src/utils/axios.ts:217]: Indeed, the corrections appear to be different from those in version 439.

I'll approve this.

**Review by itutu-tienday — APPROVED** [review]
